export type JobType = "Full-time" | "Part-time" | "Contract" | "Internship"
export type Workplace = "Remote" | "Hybrid" | "On-site"
export type Level = "Junior" | "Mid" | "Senior" | "Lead"
export type JobSource =
  | "jobs.ge"
  | "hr.ge"
  | "awork.ge"
  | "samushao.ge"
  | "unijobs.ge"
  | "myjobs.ge"
  | "hr.gov.ge"
  | "v.dk.ge"
  | "teacherjobs.ge"
  | "jobs.ss.ge"
  | "joob.ge"

export const JOB_SOURCES: { id: JobSource; label: string; logo: string }[] = [
  {
    id: "jobs.ge",
    label: "JOBS.GE",
    logo: "https://www.google.com/s2/favicons?domain=jobs.ge&sz=64",
  },
  {
    id: "hr.ge",
    label: "HR.GE",
    logo: "https://www.google.com/s2/favicons?domain=hr.ge&sz=64",
  },
  {
    id: "awork.ge",
    label: "AWORK.GE",
    logo: "https://www.google.com/s2/favicons?domain=awork.ge&sz=64",
  },
  {
    id: "samushao.ge",
    label: "SAMUSHAO.GE",
    logo: "https://www.google.com/s2/favicons?domain=samushao.ge&sz=64",
  },
  {
    id: "unijobs.ge",
    label: "UNIJOBS.GE",
    logo: "https://www.google.com/s2/favicons?domain=unijobs.ge&sz=64",
  },
  {
    id: "myjobs.ge",
    label: "MYJOBS.GE",
    logo: "https://www.google.com/s2/favicons?domain=myjobs.ge&sz=64",
  },
  {
    id: "hr.gov.ge",
    label: "HR.GOV.GE",
    logo: "https://www.google.com/s2/favicons?domain=hr.gov.ge&sz=64",
  },
  {
    id: "v.dk.ge",
    label: "V.DK.GE",
    logo: "https://www.google.com/s2/favicons?domain=v.dk.ge&sz=64",
  },
  {
    id: "teacherjobs.ge",
    label: "TEACHERJOBS.GE",
    logo: "https://www.google.com/s2/favicons?domain=teacherjobs.ge&sz=64",
  },
  {
    id: "jobs.ss.ge",
    label: "JOBS.SS.GE",
    logo: "https://www.google.com/s2/favicons?domain=jobs.ss.ge&sz=64",
  },
  {
    id: "joob.ge",
    label: "JOOB.GE",
    logo: "https://www.google.com/s2/favicons?domain=joob.ge&sz=64",
  },
]

export interface JobComment {
  id: string
  author: string
  profession: string
  avatar: string
  body: string
  postedDaysAgo: number
  relevant?: boolean
}

export interface Job {
  id: string
  title: string
  company: string
  logo: string
  location: string
  workplace: Workplace
  type: JobType
  level: Level
  category: string
  source: JobSource
  salaryMin: number
  salaryMax: number
  currency: string
  postedDaysAgo: number
  description: string
  tags: string[]
  applicants: number
  hrActive?: boolean
  /** Accepts applications without a CV / portfolio-first roles */
  cvNotRequired?: boolean
  comments?: JobComment[]
}

export const CATEGORIES = [
  "Engineering",
  "Design",
  "Product",
  "Marketing",
  "Data",
  "Sales",
  "Finance",
] as const

export const JOB_TYPES: JobType[] = ["Full-time", "Part-time", "Contract", "Internship"]
export const WORKPLACES: Workplace[] = ["Remote", "Hybrid", "On-site"]
export const LEVELS: Level[] = ["Junior", "Mid", "Senior", "Lead"]

export const JOBS: Job[] = [
  {
    id: "1",
    source: "jobs.ge",
    title: "სენიორ ფრონტენდ ინჟინერი",
    company: "თიბისი ბანკი",
    logo: "/logos/ge/tbc.png",
    location: "თბილისი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Senior",
    category: "Engineering",
    salaryMin: 4500,
    salaryMax: 6500,
    currency: "$",
    postedDaysAgo: 2,
    description:
      "შექმნი სწრაფ, დახვეწილ ინტერფეისებს React-ით და TypeScript-ით. იმუშავებ მთავარ პროდუქტის ეკრანებზე დიზაინთან და პროდუქტის გუნდთან ერთად.",
    tags: ["React", "TypeScript", "Next.js", "Tailwind"],
    applicants: 34,
    hrActive: true,
    comments: [
      {
        id: "1-1",
        author: "დავით",
        profession: "ფრონტენდ ინჟინერი",
        avatar: "https://i.pravatar.cc/96?u=davit-k",
        body: "ვინმემ იცით ტექნიკური ეტაპი როგორია? მაინტერესებს live coding არის თუ უფრო არქიტექტურის და React გამოცდილების განხილვა.",
        postedDaysAgo: 1,
        relevant: true,
      },
      {
        id: "1-2",
        author: "ელენე",
        profession: "React დეველოპერი",
        avatar: "https://i.pravatar.cc/96?u=elene-k",
        body: "ჰიბრიდული რამდენად მოქნილია? კვირაში 1 დღე ოფისში ჩემთვის იდეალური იქნებოდა.",
        postedDaysAgo: 2,
      },
      {
        id: "1-3",
        author: "თეო",
        profession: "Full-stack დეველოპერი",
        avatar: "https://i.pravatar.cc/96?u=teo-k",
        body: "ხელფასი ბრუნდება net-ად თუ gross? და trial period რამდენი თვეა?",
        postedDaysAgo: 3,
      },
    ],
  },
  {
    id: "2",
    source: "hr.ge",
    title: "პროდუქტის დიზაინერი",
    company: "საქართველოს ბანკი",
    logo: "/logos/ge/bog.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Design",
    salaryMin: 3500,
    salaryMax: 5000,
    currency: "$",
    postedDaysAgo: 1,
    description:
      "შექმნი სრულ პროდუქტულ გამოცდილებას კვლევიდან დასრულებულ ინტერფეისამდე. იმუშავებ მცირე, გამოცდილ გუნდში, სადაც მნიშვნელოვანია ხარისხი და სიცხადე.",
    tags: ["Figma", "პროტოტიპირება", "დიზაინ-სისტემები"],
    applicants: 58,
    hrActive: true,
    comments: [
      {
        id: "2-1",
        author: "მარიამ",
        profession: "UI/UX დიზაინერი",
        avatar: "https://i.pravatar.cc/96?u=mariam-k",
        body: "პორტფოლიოში მხოლოდ ვიზუალური UI ქეისები მაქვს და კვლევა ნაკლებად ჩანს. ასეთ შემთხვევაში ღირს განაცხადის გაგზავნა?",
        postedDaysAgo: 1,
        relevant: true,
      },
    ],
  },
  {
    id: "3",
    source: "awork.ge",
    title: "ბექენდ ინჟინერი",
    company: "ლიბერთი ბანკი",
    logo: "/logos/ge/liberty.png",
    location: "ქუთაისი, საქართველო",
    workplace: "On-site",
    type: "Full-time",
    level: "Mid",
    category: "Engineering",
    salaryMin: 4000,
    salaryMax: 5800,
    currency: "$",
    postedDaysAgo: 4,
    description:
      "დააპროექტებ და გააფართოებ მდგრად სერვისებს Go-სა და PostgreSQL-ზე. მნიშვნელოვანი იქნება საიმედოობა, დაკვირვებადობა და სუფთა API-ები.",
    tags: ["Go", "PostgreSQL", "Kubernetes", "gRPC"],
    applicants: 21,
    comments: [
      {
        id: "3-1",
        author: "გიორგი",
        profession: "ბექენდ ინჟინერი",
        avatar: "https://i.pravatar.cc/96?u=giorgi-k",
        body: "Go-ში 2 წელი მაქვს გამოცდილება, Kubernetes-ში კი მხოლოდ basic deploy-ები. ეს როლისთვის საკმარისი იქნება?",
        postedDaysAgo: 3,
        relevant: true,
      },
    ],
  },
  {
    id: "4",
    source: "samushao.ge",
    title: "ზრდის მარკეტინგის ლიდი",
    company: "მაგთიკომი",
    logo: "/logos/ge/magti.png",
    location: "რუსთავი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Lead",
    category: "Marketing",
    salaryMin: 3800,
    salaryMax: 5500,
    currency: "$",
    postedDaysAgo: 6,
    description:
      "მართავ ზრდის სრულ funnel-ს ფასიანი არხების, lifecycle კამპანიებისა და კონტენტის მიმართულებით. ააწყობ მონაცემებზე დაფუძნებულ ზრდის სისტემას.",
    tags: ["SEO", "ფასიანი რეკლამა", "Lifecycle", "ანალიტიკა"],
    applicants: 12,
    cvNotRequired: true,
  },
  {
    id: "5",
    source: "unijobs.ge",
    title: "მონაცემთა მეცნიერი",
    company: "სილქნეტი",
    logo: "/logos/ge/silknet.png",
    location: "დისტანციური, ევროპა",
    workplace: "Remote",
    type: "Full-time",
    level: "Senior",
    category: "Data",
    salaryMin: 5000,
    salaryMax: 7500,
    currency: "$",
    postedDaysAgo: 3,
    description:
      "გადააქცევ რთულ მონაცემებს მოდელებად, რომლებიც ბიზნესს რეალურ შედეგს აძლევს. პროდუქტის გუნდთან ერთად ბოლომდე მიიყვან ML ფუნქციებს.",
    tags: ["Python", "PyTorch", "SQL", "MLOps"],
    applicants: 47,
  },
  {
    id: "6",
    source: "jobs.ge",
    title: "პროდუქტის მენეჯერი",
    company: "თეგეტა მოტორსი",
    logo: "/logos/ge/tegeta.png",
    location: "ზუგდიდი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Senior",
    category: "Product",
    salaryMin: 4500,
    salaryMax: 6800,
    currency: "$",
    postedDaysAgo: 5,
    description:
      "განსაზღვრავ roadmap-ს და წარმართავ სხვადასხვა გუნდის მიწოდებას. მომხმარებლის საჭიროებებს გადააქცევ მკაფიო, შესრულებად გეგმად.",
    tags: ["Roadmap", "კვლევა", "ანალიტიკა"],
    applicants: 29,
    hrActive: true,
    comments: [
      {
        id: "6-1",
        author: "ნიკა",
        profession: "პროდუქტის მენეჯერი",
        avatar: "https://i.pravatar.cc/96?u=nika-k",
        body: "ხელფასის დიაპაზონი კარგია, მაგრამ მაინტერესებს decision-making რეალურად PM-ს აქვს თუ roadmap უკვე წინასწარ არის გადაწყვეტილი?",
        postedDaysAgo: 2,
        relevant: true,
      },
      {
        id: "6-2",
        author: "სოფო",
        profession: "პროდუქტის მენეჯერი",
        avatar: "https://i.pravatar.cc/96?u=sofo-k",
        body: "B2B SaaS გამოცდილება აუცილებელია? პროდუქტის მენეჯმენტი მაქვს fintech-ში, მაგრამ SaaS-ში არა.",
        postedDaysAgo: 4,
      },
      {
        id: "6-3",
        author: "ლაშა",
        profession: "Growth PM",
        avatar: "https://i.pravatar.cc/96?u=lasha-k",
        body: "ინტერვიუს პროცესი რამდენ ეტაპს მოიცავს? HR-ის შემდეგ პირდაპირ founder-თან ვხვდები?",
        postedDaysAgo: 5,
      },
    ],
  },
  {
    id: "7",
    source: "hr.ge",
    title: "ჯუნიორ UI დეველოპერი",
    company: "ვისოლი",
    logo: "/logos/ge/wissol.png",
    location: "თელავი, საქართველო",
    workplace: "On-site",
    type: "Internship",
    level: "Junior",
    category: "Engineering",
    salaryMin: 1200,
    salaryMax: 1800,
    currency: "$",
    postedDaysAgo: 1,
    description:
      "დაიწყებ კარიერას რეალური პროდუქტის ინტერფეისებზე მუშაობით გამოცდილ ინჟინრებთან ერთად. ისწავლი თანამედროვე ხელსაწყოებს და საუკეთესო პრაქტიკებს.",
    tags: ["HTML", "CSS", "JavaScript", "React"],
    applicants: 73,
    hrActive: true,
    cvNotRequired: true,
    comments: [
      {
        id: "7-1",
        author: "ლუკა",
        profession: "Junior UI დეველოპერი",
        avatar: "https://i.pravatar.cc/96?u=luka-k",
        body: "სტაჟირებისთვის კომერციული გამოცდილება აუცილებელია? React პატარა პროექტებით ვიცი, მაგრამ გუნდში ჯერ არ მიმუშავია.",
        postedDaysAgo: 1,
        relevant: true,
      },
    ],
  },
  {
    id: "8",
    source: "awork.ge",
    title: "გაყიდვების მენეჯერი",
    company: "ნიკორა",
    logo: "/logos/ge/nikora.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Contract",
    level: "Mid",
    category: "Sales",
    salaryMin: 3000,
    salaryMax: 4500,
    currency: "$",
    postedDaysAgo: 8,
    description:
      "განავითარებ ახალ გაყიდვებს საშუალო ზომის კომპანიებთან. სრულად მართავ გაყიდვების ციკლს პირველი კონტაქტიდან დახურვამდე.",
    tags: ["B2B", "SaaS", "CRM"],
    applicants: 18,
    cvNotRequired: true,
  },
  {
    id: "9",
    source: "samushao.ge",
    title: "ფინანსური ანალიტიკოსი",
    company: "რედბერი",
    logo: "/logos/ge/redberry.png",
    location: "მცხეთა, საქართველო",
    workplace: "Hybrid",
    type: "Part-time",
    level: "Mid",
    category: "Finance",
    salaryMin: 2500,
    salaryMax: 3800,
    currency: "$",
    postedDaysAgo: 10,
    description:
      "იმუშავებ ბიუჯეტირებაზე, პროგნოზირებასა და ანგარიშგებაზე. ააწყობ მოდელებს, რომლებიც მენეჯმენტს სწორ გადაწყვეტილებებში ეხმარება.",
    tags: ["Excel", "მოდელირება", "ანგარიშგება"],
    applicants: 9,
    cvNotRequired: true,
  },
  {
    id: "10",
    source: "unijobs.ge",
    title: "პლატფორმის წამყვანი ინჟინერი",
    company: "გორგია",
    logo: "/logos/ge/gorgia.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Full-time",
    level: "Lead",
    category: "Engineering",
    salaryMin: 6500,
    salaryMax: 9000,
    currency: "$",
    postedDaysAgo: 2,
    description:
      "უხელმძღვანელებ cloud პლატფორმის არქიტექტურას. განსაზღვრავ ტექნიკურ მიმართულებას და აამაღლებ ინჟინერიის ხარისხს.",
    tags: ["AWS", "Terraform", "Go", "განაწილებული სისტემები"],
    applicants: 26,
    hrActive: true,
    comments: [
      {
        id: "10-1",
        author: "ანა",
        profession: "DevOps ინჟინერი",
        avatar: "https://i.pravatar.cc/96?u=ana-k",
        body: "ლიდის პოზიციაზე hands-on coding რამდენია? მენეჯმენტი მაინტერესებს, მაგრამ კოდისგან სრულად მოშორება არ მინდა.",
        postedDaysAgo: 1,
        relevant: true,
      },
    ],
  },
  {
    id: "11",
    source: "jobs.ge",
    title: "მობილური დეველოპერი",
    company: "პროკრედიტ ბანკი",
    logo: "/logos/ge/procredit.png",
    location: "თბილისი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Mid",
    category: "Engineering",
    salaryMin: 3200,
    salaryMax: 4800,
    currency: "$",
    postedDaysAgo: 1,
    description: "ვაკანსია მობილური დეველოპერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["React Native", "TypeScript"],
    applicants: 16,
  },
  {
    id: "12",
    source: "hr.ge",
    title: "QA ინჟინერი",
    company: "თინეთი",
    logo: "/logos/ge/tnet.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Engineering",
    salaryMin: 2800,
    salaryMax: 4000,
    currency: "$",
    postedDaysAgo: 2,
    description: "ვაკანსია QA ინჟინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Playwright", "CI/CD"],
    applicants: 23,
  },
  {
    id: "13",
    source: "awork.ge",
    title: "კონტენტ მარკეტერი",
    company: "მაიავტო",
    logo: "/logos/ge/myauto.png",
    location: "ქუთაისი, საქართველო",
    workplace: "On-site",
    type: "Part-time",
    level: "Junior",
    category: "Marketing",
    salaryMin: 1800,
    salaryMax: 2600,
    currency: "$",
    postedDaysAgo: 3,
    description: "ვაკანსია კონტენტ მარკეტერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["კონტენტი", "SEO"],
    applicants: 30,
  },
  {
    id: "14",
    source: "samushao.ge",
    title: "DevOps ინჟინერი",
    company: "ქართული ავიახაზები",
    logo: "/logos/ge/airways.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Contract",
    level: "Senior",
    category: "Engineering",
    salaryMin: 5000,
    salaryMax: 7200,
    currency: "$",
    postedDaysAgo: 4,
    description: "ვაკანსია DevOps ინჟინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["AWS", "Docker", "K8s"],
    applicants: 37,
  },
  {
    id: "15",
    source: "unijobs.ge",
    title: "UX რესერჩერი",
    company: "იმედი",
    logo: "/logos/ge/imedi.png",
    location: "გორი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Mid",
    category: "Design",
    salaryMin: 3000,
    salaryMax: 4500,
    currency: "$",
    postedDaysAgo: 5,
    description: "ვაკანსია UX რესერჩერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["კვლევა", "ინტერვიუები"],
    applicants: 44,
  },
  {
    id: "16",
    source: "jobs.ge",
    title: "კლიენტების წარმატების მენეჯერი",
    company: "თიბისი ბანკი",
    logo: "/logos/ge/tbc.png",
    location: "ზუგდიდი, საქართველო",
    workplace: "Hybrid",
    type: "Internship",
    level: "Mid",
    category: "Sales",
    salaryMin: 2500,
    salaryMax: 3800,
    currency: "$",
    postedDaysAgo: 6,
    description: "ვაკანსია კლიენტების წარმატების მენეჯერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["CSM", "SaaS"],
    applicants: 51,
  },
  {
    id: "17",
    source: "hr.ge",
    title: "ფრონტენდ ინჟინერი",
    company: "საქართველოს ბანკი",
    logo: "/logos/ge/bog.png",
    location: "დისტანციური, ევროპა",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Engineering",
    salaryMin: 3500,
    salaryMax: 5200,
    currency: "$",
    postedDaysAgo: 7,
    description: "ვაკანსია ფრონტენდ ინჟინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Vue", "TypeScript"],
    applicants: 58,
  },
  {
    id: "18",
    source: "awork.ge",
    title: "HR ბიზნეს პარტნიორი",
    company: "ლიბერთი ბანკი",
    logo: "/logos/ge/liberty.png",
    location: "ფოთი, საქართველო",
    workplace: "On-site",
    type: "Full-time",
    level: "Senior",
    category: "Product",
    salaryMin: 2800,
    salaryMax: 4200,
    currency: "$",
    postedDaysAgo: 8,
    description: "ვაკანსია HR ბიზნეს პარტნიორი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["HR", "რეკრუტინგი"],
    applicants: 65,
  },
  {
    id: "19",
    source: "samushao.ge",
    title: "ბიზნეს ანალიტიკოსი",
    company: "მაგთიკომი",
    logo: "/logos/ge/magti.png",
    location: "დისტანციური, ევროპა",
    workplace: "Remote",
    type: "Part-time",
    level: "Mid",
    category: "Finance",
    salaryMin: 2700,
    salaryMax: 4000,
    currency: "$",
    postedDaysAgo: 9,
    description: "ვაკანსია ბიზნეს ანალიტიკოსი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["SQL", "Excel"],
    applicants: 72,
  },
  {
    id: "20",
    source: "unijobs.ge",
    title: "გრაფიკული დიზაინერი",
    company: "სილქნეტი",
    logo: "/logos/ge/silknet.png",
    location: "მარნეული, საქართველო",
    workplace: "Hybrid",
    type: "Contract",
    level: "Junior",
    category: "Design",
    salaryMin: 1500,
    salaryMax: 2300,
    currency: "$",
    postedDaysAgo: 10,
    description: "ვაკანსია გრაფიკული დიზაინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Illustrator", "Figma"],
    applicants: 79,
  },
  {
    id: "21",
    source: "jobs.ge",
    title: "სრულ სტეკის დეველოპერი",
    company: "თეგეტა მოტორსი",
    logo: "/logos/ge/tegeta.png",
    location: "თბილისი, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Senior",
    category: "Engineering",
    salaryMin: 4800,
    salaryMax: 7000,
    currency: "$",
    postedDaysAgo: 11,
    description: "ვაკანსია სრულ სტეკის დეველოპერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Node.js", "React"],
    applicants: 6,
  },
  {
    id: "22",
    source: "hr.ge",
    title: "ოფისის მენეჯერი",
    company: "ვისოლი",
    logo: "/logos/ge/wissol.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Internship",
    level: "Junior",
    category: "Sales",
    salaryMin: 1400,
    salaryMax: 2000,
    currency: "$",
    postedDaysAgo: 12,
    description: "ვაკანსია ოფისის მენეჯერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["ადმინისტრაცია"],
    applicants: 13,
  },
  {
    id: "23",
    source: "awork.ge",
    title: "მონაცემთა ანალიტიკოსი",
    company: "ნიკორა",
    logo: "/logos/ge/nikora.png",
    location: "ქუთაისი, საქართველო",
    workplace: "On-site",
    type: "Full-time",
    level: "Mid",
    category: "Data",
    salaryMin: 3200,
    salaryMax: 4800,
    currency: "$",
    postedDaysAgo: 1,
    description: "ვაკანსია მონაცემთა ანალიტიკოსი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["SQL", "Python", "Tableau"],
    applicants: 20,
  },
  {
    id: "24",
    source: "samushao.ge",
    title: "პროექტის მენეჯერი",
    company: "რედბერი",
    logo: "/logos/ge/redberry.png",
    location: "დისტანციური, გლობალურად",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Product",
    salaryMin: 3000,
    salaryMax: 4500,
    currency: "$",
    postedDaysAgo: 2,
    description: "ვაკანსია პროექტის მენეჯერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Agile", "Jira"],
    applicants: 27,
  },
  {
    id: "25",
    source: "unijobs.ge",
    title: "სოციალური მედიის მენეჯერი",
    company: "გორგია",
    logo: "/logos/ge/gorgia.png",
    location: "გორი, საქართველო",
    workplace: "Hybrid",
    type: "Part-time",
    level: "Junior",
    category: "Marketing",
    salaryMin: 1600,
    salaryMax: 2400,
    currency: "$",
    postedDaysAgo: 3,
    description: "ვაკანსია სოციალური მედიის მენეჯერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["SMM", "კონტენტი"],
    applicants: 34,
  },
  {
    id: "26",
    source: "jobs.ge",
    title: "უსაფრთხოების ინჟინერი",
    company: "პროკრედიტ ბანკი",
    logo: "/logos/ge/procredit.png",
    location: "ზუგდიდი, საქართველო",
    workplace: "Hybrid",
    type: "Contract",
    level: "Senior",
    category: "Engineering",
    salaryMin: 5500,
    salaryMax: 8000,
    currency: "$",
    postedDaysAgo: 4,
    description: "ვაკანსია უსაფრთხოების ინჟინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["Security", "Pentest"],
    applicants: 41,
  },
  {
    id: "27",
    source: "hr.ge",
    title: "იურისტი",
    company: "თინეთი",
    logo: "/logos/ge/tnet.png",
    location: "დისტანციური, ევროპა",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Finance",
    salaryMin: 2500,
    salaryMax: 4000,
    currency: "$",
    postedDaysAgo: 5,
    description: "ვაკანსია იურისტი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["კონტრაქტები"],
    applicants: 48,
  },
  {
    id: "28",
    source: "awork.ge",
    title: "ანგარიშების მენეჯერი",
    company: "მაიავტო",
    logo: "/logos/ge/myauto.png",
    location: "ფოთი, საქართველო",
    workplace: "On-site",
    type: "Internship",
    level: "Mid",
    category: "Sales",
    salaryMin: 2200,
    salaryMax: 3500,
    currency: "$",
    postedDaysAgo: 6,
    description: "ვაკანსია ანგარიშების მენეჯერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["B2B", "CRM"],
    applicants: 55,
  },
  {
    id: "29",
    source: "samushao.ge",
    title: "AI ინჟინერი",
    company: "ქართული ავიახაზები",
    logo: "/logos/ge/airways.png",
    location: "დისტანციური, ევროპა",
    workplace: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Engineering",
    salaryMin: 4200,
    salaryMax: 6000,
    currency: "$",
    postedDaysAgo: 7,
    description: "ვაკანსია AI ინჟინერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["LLM", "Python"],
    applicants: 62,
  },
  {
    id: "30",
    source: "unijobs.ge",
    title: "რეკრუტერი",
    company: "იმედი",
    logo: "/logos/ge/imedi.png",
    location: "მარნეული, საქართველო",
    workplace: "Hybrid",
    type: "Full-time",
    level: "Junior",
    category: "Product",
    salaryMin: 1800,
    salaryMax: 2800,
    currency: "$",
    postedDaysAgo: 8,
    description: "ვაკანსია რეკრუტერი პოზიციაზე — იმუშავებ გამოცდილ გუნდთან ერთად.",
    tags: ["რეკრუტინგი"],
    applicants: 69,
  }
]
